# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

SENDGRID_PASSWORD: qqc0ogs7
SENDGRID_USERNAME: app26978735@heroku.com
DEVISE_SECRET_KEY: ca475e82bad6b10ba3187de2be58adf8e6fb9d3b4a0bc329cb6383151bb703d4a22853dbd8e8f92696fcba1a1b996ee24e32bf4b4c2985b809cf6342ad79afe4